# Project information

site_name: Windows on AWS Workshops
site_description: 'A collection of Windows on AWS workshops'
site_author: 'aws-ent-workshops@amazon.com'
site_url: 'https://awsentworkshops.com'

# Repository
repo_name: 'aws-samples/aws-workshop-for-win-dotnet-mssql'
repo_url: 'https://github.com/aws-samples/aws-workshop-for-win-dotnet-mssql'

# Copyright
copyright: '&copy; 2019, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/aws_smile_logo.png'
  favicon: 'assets/images/aws-favicon.ico'
  feature:
    tabs: true
  custom_dir: 'docs/theme'

# Customization
extra_css:
  - 'stylesheets/custom.css'
extra_javascript:
  - 'javascripts/extra.js'
extra:
  social:
    - type: 'home'
      link: 'https://awsentworkshops.com'
    - type: 'globe'
      link: 'https://aws.amazon.com/windows/'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details

# Navigation
nav:
  - Home: 'index.md'
  - Getting Started: 'getting-started.md'
  - re:Invent 2018:
    - Directory: 'reinvent/index2018.md'
      - WIN319 Active Directory Domain Trusts and AWS SSO Jumpstart: 
        - Home: 'reinvent/win319/index.md'
        - Prerequisites: 'reinvent/win319/prereq.md'
        - User Instructions:
          - Deploying AD-DS on EC2: 'reinvent/win319/1_DeployAd.md'
          - Deploy AWS Managed AD: 'reinvent/win319/2_DeployMad.md'
          - Setup 2-way trust: 'reinvent/win319/3_Trust.md'
          - Create AWS Organization: 'reinvent/win319/4_Createorg.md'
          - Connect your directory to AWS SSO: 'reinvent/win319/5_ConnectADtoSSO.md'
          - Verify AWS SSO access to AWS account: 'reinvent/win319/6_VerifyADSSO_MAD.md'
  - re:Invent 2019:
    - Directory: 'reinvent/index2019.md'
  - Builder Sessions:
    - Directory: 'builder-sessions/index.md'
  - Full Day Workshops: 
    - Directory: 'workshops/index.md'
  - Contributing: 'contribute.md'
  - License: 'license.md'
