# Project information

site_name: Windows on AWS Workshops
site_description: 'A collection of Windows on AWS workshops'
site_author: 'aws-ent-workshops@amazon.com'
site_url: 'https://awsentworkshops.com'

# Repository
repo_name: 'aws-samples/aws-workshop-for-win-dotnet-mssql'
repo_url: 'https://github.com/aws-samples/aws-workshop-for-win-dotnet-mssql'

# Copyright
copyright: '&copy; 2019, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/aws_smile_logo.png'
  favicon: 'assets/images/aws-favicon.ico'
  feature:
    tabs: true
  custom_dir: 'docs/theme'

# Customization
extra_css:
  - 'stylesheets/custom.css'
extra_javascript:
  - 'javascripts/extra.js'
extra:
  social:
    - type: 'home'
      link: 'https://awsentworkshops.com'
    - type: 'globe'
      link: 'https://aws.amazon.com/windows/'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - sane_lists

# Navigation
nav:
  - Home: 'index.md'
  - Getting Started: 'getting-started.md'
  - Workshops:
      - Directory: 'workshops/index.md'
      - Introductory Microsoft Windows on AWS: 'workshops/IntroToWinAWS/index.md'
      - Migrating Microsoft Windows to AWS: 'workshops/MigrateWindowsToAWS/index.md'
      - Migrating Microsoft SQL to AWS: 'workshops/MigrateSQLToAWS/index.md'
      - Managing Microsoft Windows like a Pro: 'workshops/ManageWindowsPro/index.md'
  - Immersion Days (Coming Soon):
      - Directory: 'ImmersionDays/index.md'
      - Raw List: 'ImmersionDays/labs/index.md'
      - Windows: 'ImmersionDays/windows/index.md'
      - .Net: 'ImmersionDays/dotnet/index.md'
  - Contributing: 'contribute.md'
  - License: 'license.md'
